# Agents designed into the interface, 2025–2026.
AGENT = [
 dict(key='cocoa', group='agent', motif='list', short='Cocoa',
  title='Cocoa: co-planning and co-execution with AI agents',
  meta='CHI 2026; arXiv 2412.10999 · Feng, Pu, Latzke, August, Siangliulue, Bragg, Weld, Zhang, Chang',
  url='https://arxiv.org/abs/2412.10999',
  summary='The agent lives inside a research document as a shared plan whose steps can be assigned to person or agent, executed and re-executed notebook-style, with planning and execution interleaved. A lab study of sixteen and a one-week field deployment of seven.',
  stance='Roles, progress and handoff are document structure, not a sidebar: the designed unit is the shared plan in the document.'),
 dict(key='magentic', group='agent', motif='screen', short='Magentic-UI',
  title='Magentic-UI: towards human-in-the-loop agentic systems',
  meta='arXiv 2507.22358, July 2025 · Mozannar, Bansal, Tan, Fourney, Dibia, Chen et al. (Microsoft Research)',
  url='https://arxiv.org/abs/2507.22358',
  summary='An open-source web agent interface built around co-planning (an editable plan before execution), co-tasking (pause, feedback, take over the browser), multi-tasking, action guards with user-set frequency, and long-term memory. Evaluated on benchmarks, simulated users, user studies and safety.',
  stance='The most explicit catalogue of agentic UI patterns (progress, approval, handoff, background parallelism) as designed mechanisms.'),
 dict(key='domsteer', group='agent', motif='screen', short='DOMSteer',
  title='Beyond chat and clicks: GUI agents for in-situ assistance via live interface transformation',
  meta='arXiv 2604.14668, April 2026 · Hao, Selvakumaran, Sun, Wang',
  url='https://arxiv.org/abs/2604.14668',
  summary='A browser-extension agent grounds a help request to UI elements and performs reversible DOM manipulations directly on the live page (tooltips, highlighting, layout reorganisation) without modifying the app. Contributes a design space of how agents insert, mutate or recompose web elements, and beats a ChatGPT Atlas baseline on two complex tools.',
  stance='The agent\'s output is a modification of the interface it acts in; the designed unit is the space of allowed in-situ transformations.'),
 dict(key='agentuxlab', group='agent', motif='grid', short='AgentUXlab',
  title='Understanding user experiences of computer use agents: design space and opportunities for building agent UX prototypes',
  meta='arXiv 2510.04452, Oct 2025, revised July 2026 · Liang, Barik, Nichols, Schoop, Cheng',
  url='https://arxiv.org/abs/2510.04452',
  summary='Argues that computer-use agent research trains and evaluates models and leaves the agents\' user experience understudied. A taxonomy of 21 UX considerations, requirements from twelve participants, and a probe for prototyping different agent UX approaches on a website.',
  stance='Agent UX itself becomes a prototyping target with its own design space and tooling.'),
 dict(key='agentheur', group='agent', motif='list', short='Heuristics for agents',
  title='Augmenting interface usability heuristics for reliable computer-use agents',
  meta='arXiv 2605.02729, May 2026 · Liu et al.',
  url='https://arxiv.org/abs/2605.02729',
  summary='Re-reads Nielsen\'s heuristics for agents as users, proposes safe additive augmentations to an interface, and a test suite for them.',
  stance='Interfaces are now designed for two users, one of them an agent, which doubles the audience of every design decision.'),
 dict(key='msagents', group='agent', motif='chat', short='Microsoft Design on agents',
  title='UX design for agents',
  meta='Microsoft Design, April 2025 · He, Fox, Snellinger',
  url='https://microsoft.design/articles/ux-design-for-agents/',
  summary='Microsoft\'s design organisation on what changes when the product has an agent in it: how to show what it is doing, where it should ask, and how to keep the person in the loop without making them the loop.',
  stance='The agent as a first-class design subject, with progress and consent as the patterns to get right.'),
 dict(key='linearaig', group='agent', motif='list', short='Linear AIG',
  title='Agent interaction guidelines',
  meta='Linear, living document, 2025 · Karri Saarinen',
  url='https://linear.app/developers/aig',
  summary='Six principles for agents as teammates: disclose identity, work through existing platform UI patterns natively, give immediate feedback, expose state, respect disengagement, and an agent cannot be held accountable.',
  stance='The opposite pole to generative UI: agents act inside a fixed, human-designed interface and generate no UI at all.'),
 dict(key='anthropicmerge', group='agent', motif='chat', short='Claude merges chat and Cowork',
  title='Anthropic merges Claude chat, Cowork, artifacts and Claude Design in one interface',
  meta='TechCrunch, 16 Sept 2026 · Ivan Mehta, on Anthropic',
  url='https://techcrunch.com/2026/09/16/anthropic-merges-claude-chat-and-cowork-in-one-interface/',
  summary='Chat, the agentic Cowork product, artifacts and Claude Design are unified, and Claude routes requests itself because customers struggled to choose the right tab for the task. Agent tasks start on desktop and are monitored on mobile.',
  stance='The agent is not a mode: routing between conversation, background work and generated artefacts is done by the model, and progress becomes a cross-device UI element.'),
 dict(key='canvasagents', group='agent', motif='screen', short='Notion and Cursor agents',
  title='Agents in the workspace: Notion 3.0 agents and Cursor cloud agents',
  meta='Notion, Sept 2025; Cursor, 2026',
  url='https://www.notion.com/releases/2025-09-18',
  summary='Notion\'s agent creates and updates pages and databases at scale, runs twenty-minute multi-step actions and keeps its memory in dedicated pages, with custom agents on schedules. Cursor\'s cloud agents run in sandboxes, hand off plans between local and cloud, verify their own work by remote desktop control, and report back as videos, screenshots and logs.',
  stance='The designed unit is the point of contact between agent work and an existing surface, with undo as the universal safety pattern and approval largely absent.'),
]
