# Design theory and practitioner discourse, 2023–2026.
DISC = [
 dict(key='nielsen2023', group='disc', motif='chat', short='Nielsen 2023',
  title='AI: first new UI paradigm in 60 years',
  meta='Nielsen Norman Group, June 2023 · Jakob Nielsen',
  url='https://www.nngroup.com/articles/ai-paradigm/',
  summary='Names the third UI paradigm after batch and command-based GUI: the person no longer tells the computer what to do but what outcome they want. Predicts hybrids that mix intent specification with GUI elements rather than the death of the GUI.',
  stance='The founding term for the outcome position: intent-based outcome specification.'),
 dict(key='nng', group='disc', motif='list', short='NN/g Generative UI',
  title='Generative UI and outcome-oriented design',
  meta='Nielsen Norman Group, March 2024 · Kate Moran, Sarah Gibbons',
  url='https://www.nngroup.com/articles/generative-ui/',
  summary='Defines generative UI as an interface generated in real time by AI to fit the person\'s needs and context. Designers shift from designing interfaces to designing outcomes and become designers of parameters and constraints, sorting content into must show, should show, never show. Flags that constantly changing UIs will cause usability problems.',
  stance='The canonical practitioner statement of design the space, not the screen: the designer\'s deliverable is parameters and constraints.'),
 dict(key='nielsena11y', group='disc', motif='side', short='Nielsen on accessibility',
  title='Accessibility has failed: try generative UI = individualized UX',
  meta='Jakob Nielsen on UX (Substack), Feb 2024 · Jakob Nielsen',
  url='https://jakobnielsenphd.substack.com/p/accessibility-generative-ui',
  summary='Claims thirty years of accessibility practice failed because one two-dimensional design is linearised for everyone, and that second-generation generative UI would build a different interface per person. Concedes the loss of exact designer control. The comment thread carries the counter-arguments, including how individualised UIs work on shared devices.',
  stance='Individualised UX as the accessibility argument; the shared-device objection first appears here, in the comments.'),
 dict(key='a16z', group='disc', motif='figure', short='a16z',
  title='How generative AI is remaking UI/UX design',
  meta='Andreessen Horowitz, May 2024 · Jennifer Li, Yoko Li',
  url='https://a16z.com/how-generative-ai-is-remaking-ui-ux-design/',
  summary='A venture map of design-to-code tooling that ends with a run-time claim: UI components are functions that give a model a visual state space to explore, and for apps where the API and data model are fixed the interface can largely be inferred instead of designed.',
  stance='The strongest version of the designer dropping out: UI inferred rather than designed.'),
 dict(key='appleton', group='disc', motif='screen', short='Home-cooked software',
  title='Home-cooked software and barefoot developers',
  meta='Local-First Conf keynote, May 2024 · Maggie Appleton',
  url='https://maggieappleton.com/home-cooked-software',
  summary='Language models open a golden age for barefoot developers, technically curious non-professionals serving the long tail of needs that industrial software ignores. Models are disconnected Lego pieces that need orchestration and supportive tools, and local-first architectures should be the default underneath.',
  stance='Personal software made by its users: the interface is bespoke because a person made it, not because a model generated it at run time.'),
 dict(key='clark', group='disc', motif='screen', short='Sentient Design',
  title='Sentient design: AI and the next chapter of UX',
  meta='Big Medium talk (2024); book with Veronika Kindred, Rosenfeld Media, 2026 · Josh Clark',
  url='https://bigmedium.com/speaking/sentient-design-josh-clark-talk.html',
  summary='Defines sentient design as intelligent interfaces aware of context and intent that deliver radically adaptive experiences, morphing content, structure, interaction or all three. Designers treat AI as a design material and guide its behaviour through design systems and constraints, amplifying judgment rather than replacing it.',
  stance='AI as design material and the designer as director: adaptation inside a designed system.'),
 dict(key='saarinen', group='disc', motif='screen', short='Linear workbench',
  title='Design for the AI age',
  meta='Linear, April 2025 · Karri Saarinen',
  url='https://linear.app/now/design-for-the-ai-age',
  summary='Deterministic UI design meets an unpredictable technology, but chat is not the AI-native answer: it is weak and generic and sits outside workflows. Proposes the workbench, a functional application with traditional UI where AI is a tool inside it. Form sets the context, so design has to draw boundaries.',
  stance='The workbench objection: keep the stable frame and put the model inside it.'),
 dict(key='inkswitch', group='disc', motif='list', short='Malleable software',
  title='Malleable software: restoring user agency in a world of locked-down apps',
  meta='Ink & Switch essay, June 2025 · Litt, Horowitz, van Hardenberg, Matthews',
  url='https://www.inkandswitch.com/essay/malleable-software/',
  summary='A manifesto for software people can reshape with minimal friction: gentle slopes from use to creation, composable tools over shared data, community-maintained software. AI code generation alone does not remove the barriers; bringing it into today\'s ecosystem is like bringing a talented sous chef to a food court. It helped inside Patchwork only because persistence, collaboration and composition were already there.',
  stance='Malleability first: the person, not the model, changes the interface, and AI is a complement to a malleable substrate.'),
 dict(key='nielsengemini', group='disc', motif='chat', short='Nielsen on Gemini',
  title='Generative UI from Gemini 3 Pro',
  meta='Jakob Nielsen on UX (Substack), Nov 2025 · Jakob Nielsen',
  url='https://jakobnielsenphd.substack.com/p/generative-ui-google',
  summary='Reads Google\'s launch as mainstreaming individualisation: an interaction synthesiser that strips navigation and shows only what the immediate intent needs, which he calls cheap, disposable UI. Predicts AI beats human designers on simple problems by late 2026 and declares the end of traditional UI design and the rise of UX anthropology.',
  stance='Cheap disposable UI, the end of UI design as a screen-making craft.'),
 dict(key='wong', group='disc', motif='screen', short='Wong on ephemeral UI',
  title='Generative UI and the ephemeral interface',
  meta='rogerwong.me, Nov 2025 · Roger Wong',
  url='https://rogerwong.me/2025/11/generative-ui-and-the-ephemeral-interface',
  summary='A practitioner reading of the same launch. Gemini generates presentations of content, not new app chrome, so it works more like content than UI, and that is the only version that survives Nielsen\'s own consistency heuristic. Asks what happens when you are shown a different UI every time, and who supports it.',
  stance='The consistency objection, and the distinction between generated content and generated chrome.'),
 dict(key='nielsen2026', group='disc', motif='list', short='Nielsen 2026',
  title='18 predictions for 2026, with the companion essay No more user interface?',
  meta='Jakob Nielsen on UX (Substack), Jan 2026 and May 2025 · Jakob Nielsen',
  url='https://jakobnielsenphd.substack.com/p/2026-predictions',
  summary='Interfaces are no longer hard-coded but drawn in real time from intent, context and history; designers move from designing screens to editing system behaviour through constraints and design tokens. Names the review paradox (verifying an agent is harder than doing the task) and lists new design objects: policy surfaces, confidence conveyors, system temperament.',
  stance='Editing system behaviour: constraints, tokens, policy surfaces and temperament as the design object.'),
 dict(key='moore', group='disc', motif='grid', short='Builder.io',
  title='Designing generative UI in an agent-native world',
  meta='Builder.io blog, May 2026 · Alice Moore',
  url='https://www.builder.io/blog/designing-generative-ui-in-an-agent-native-world',
  summary='The tooling vendor\'s version of the constraints position: stop tweaking individual layouts and teach the machine why, when and how to deploy visual patterns through elastic primitives with explicit layout, responsive and spatial guardrails. Design systems become machine-legible metadata baked into the component\'s API schema.',
  stance='The machine-legible design system as the design object.'),
 dict(key='hall', group='disc', motif='grid', short='Three things, one ships',
  title='Generative UI is three things. Only one ships.',
  meta='DEV Community, June 2026 · Joshua Hall',
  url='https://dev.to/joshjhall/generative-ui-is-three-things-only-one-ships-n66',
  summary='Splits GenUI into full code generation (does not ship: stochastic, slow, inconsistent), component-library selection (still gives the model too much authority over layout and field order), and the bounded dynamic surface: a human-designed deterministic core with the model picking among a few dozen widgets inside a contained region. Argues for about 80% familiar and 20% dynamic.',
  stance='The bounded dynamic surface: generation inside a stable frame, sized so the damage stays where the person can ignore it.'),
 dict(key='berman', group='disc', motif='grid', short='CopilotKit three kinds',
  title='The three types of generative UI',
  meta='CopilotKit blog, Sept 2025 · Eli Berman',
  url='https://www.copilotkit.ai/blog/the-three-kinds-of-generative-ui',
  summary='The industry taxonomy that later essays react to: static generative UI (pre-built components the model fills), declarative (the model composes from a schema), and open-ended (the model writes code). Its rule: the more freedom you give the model, the more you must invest in guardrails.',
  stance='Freedom and guardrails as a single dial; the taxonomy most engineering teams now use to place themselves.'),
 dict(key='wattenberger', group='disc', motif='chat', short='Wattenberger',
  title='Why chatbots are not the future of interfaces',
  meta='wattenberger.com, May 2023 · Amelia Wattenberger',
  url='https://wattenberger.com/thoughts/boo-chatbots/',
  summary='Text inputs have no affordances: a blank box tells you nothing about what it can do or how to say it. Argues for more tools and fewer operated machines, with the model\'s power delivered through direct, legible controls.',
  stance='The affordance objection to chat, which every later argument for generated controls rests on.'),
]
