# Industry products, SDKs, protocols and guidelines, 2024–2026.
IND = [
 dict(key='gemini', group='ind', motif='screen', short='Gemini generative UI',
  title='Generative UI in the Gemini app and AI Mode: dynamic view, visual layout, and the Neural Expressive redesign',
  meta='Google, Nov 2025 launch; app redesign May 2026',
  url='https://research.google/blog/generative-ui-a-rich-custom-visual-interactive-user-experience-for-any-prompt/',
  summary='Gemini 3 Pro with agentic coding, server-side tools and a long system instruction generates complete pages, tools and games per prompt, then post-processes them. Shipped the same day as dynamic view and visual layout in the Gemini app and in AI Mode for US subscribers. In May 2026 the app began laying out every response at run time with imagery, timelines and dynamic graphics for all users. Admitted limits: generation can take over a minute, and occasional inaccuracies.',
  stance='The model authors whole interfaces as code from scratch; the guardrails are Google\'s system prompt, post-processing and house design system, none of them exposed to developers.'),
 dict(key='searchgenui', group='ind', motif='screen', short='Search mini apps',
  title='Generative UI across Google Search: I/O 2026 expansion and the AI Overviews rollout',
  meta='Google, May and Aug 2026',
  url='https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/',
  summary='With Antigravity and Gemini 3.5 Flash, Search builds a custom format for a question on the fly, assembling interactive visuals, tables, graphs and simulations, and keeps persistent mini apps such as dashboards and trackers. In August 2026 generative UI moved from AI Mode into AI Overviews in English worldwide, framed around study features.',
  stance='Free generation of whole answer surfaces by a first-party model, now on by default; no third party authors anything and persistence is the new promise.'),
 dict(key='a2ui', group='ind', motif='grid', short='A2UI',
  title='A2UI, the Agent-to-User Interface protocol, and the Flutter GenUI SDK',
  meta='Google with CopilotKit, Dec 2025; v0.9.1 in 2026',
  url='https://developers.googleblog.com/introducing-a2ui-an-open-project-for-agent-driven-interfaces/',
  summary='A flat JSON list of components with ID references and a separate data model, streamed incrementally, that a client maps onto its own Angular, Flutter, React or Lit widgets. A declarative data format, not executable code: agents can only use pre-approved components from your catalog. Used in Google Opal and Gemini Enterprise; Apache 2.0.',
  stance='The model composes from a client-owned catalog and the client, not the agent, holds the guardrails. The catalog is the designed artefact.'),
 dict(key='appssdk', group='ind', motif='chat', short='OpenAI Apps SDK',
  title='Apps in ChatGPT and the Apps SDK, renamed plugins in July 2026',
  meta='OpenAI, DevDay Oct 2025; docs fetched Sept 2026',
  url='https://developers.openai.com/apps-sdk/build/custom-ux',
  summary='A React bundle runs in an iframe and talks to the developer\'s MCP server over the MCP Apps JSON-RPC bridge, with four display modes (inline card, carousel, fullscreen, picture-in-picture) and a window.openai surface for checkout, files and widget state. The July 2026 rename of the App Directory to the Plugin Directory changed packaging, not protocol. DevDay 2026 is on 29 September and has not happened yet.',
  stance='The developer authors the whole widget and the model only decides when to call it; OpenAI holds the frame, the display modes and the content security policy.'),
 dict(key='chatkit', group='ind', motif='grid', short='ChatKit widgets',
  title='ChatKit widgets: a fixed JSON vocabulary for agent-emitted UI',
  meta='OpenAI AgentKit, Oct 2025',
  url='https://developers.openai.com/api/docs/guides/chatkit-widgets',
  summary='A closed set of containers (Card, ListView) and nodes (Badge, Row, Col, Button, DatePicker, Form, Markdown, Select, Text, Transition and so on) that a backend emits and ChatKit renders, with a visual widget builder that produces the JSON. CopilotKit describes an Open-JSON-UI standard derived from it, but no OpenAI-published spec was found; treat that provenance as unverified.',
  stance='Slot-filling from a closed component set: OpenAI owns the vocabulary and the rendering, and the developer or the model fills it.'),
 dict(key='mcpapps', group='ind', motif='screen', short='MCP Apps',
  title='MCP Apps: interactive tool UIs in Claude, ChatGPT, VS Code and Microsoft 365 Copilot',
  meta='Anthropic, OpenAI and the MCP-UI community, Jan 2026; formalised as an extension July 2026',
  url='https://blog.modelcontextprotocol.io/posts/2026-01-26-mcp-apps/',
  summary='A tool declares a ui:// resource that carries bundled HTML and JavaScript; hosts render it in a sandboxed iframe with JSON-RPC over postMessage, and the model stays in the loop, seeing what people do. Nine launch partners including Slack, Figma and Canva. Hosts already diverge: Claude requires domain signing and offers fullscreen, ChatGPT at first lacked UI-initiated tool calls, VS Code lacked fullscreen.',
  stance='Developer-authored web UI inside a host sandbox, with the host holding the guardrails: sandbox, pre-declared templates, consent for UI-initiated calls.'),
 dict(key='claudedesign', group='ind', motif='screen', short='Claude Design',
  title='Claude artifacts and Claude Design',
  meta='Anthropic, artifacts June 2024 and June 2025; Claude Design April 2026',
  url='https://www.anthropic.com/news/claude-design-anthropic-labs',
  summary='Artifacts let the model build working apps in the conversation and, from June 2025, call Claude from inside themselves. Claude Design, an Anthropic Labs preview, produces prototypes, slides, one-pagers and mockups, and onboards a team\'s design system by reading its codebase and design files so that colours, typography and components are used automatically.',
  stance='The model authors whole interfaces as code at design or conversation time; the guardrail is an ingested design system plus the person, not a run-time catalog.'),
 dict(key='vercel', group='ind', motif='grid', short='Vercel AI SDK',
  title='Vercel AI SDK generative UI, from 3.0 to v7, and v0',
  meta='Vercel, March 2024 onward',
  url='https://ai-sdk.dev/docs/ai-sdk-ui/generative-user-interfaces',
  summary='The industry origin of the term: stream React components from LLMs. In v7 a chat message carries typed tool parts with states (input available, output available, error), each mapped by the developer to a component; the server-component route is now marked experimental. v0 separately lets the model author whole apps at design time.',
  stance='The model chooses a tool and the developer owns every component; whole-app generation is kept at design time.'),
 dict(key='thesys', group='ind', motif='grid', short='thesys C1',
  title='thesys C1 generative UI API',
  meta='Thesys, April 2025',
  url='https://www.infoworld.com/article/3971182/thesys-introduces-generative-ui-api-for-building-ai-apps.html',
  summary='Sits in front of any LLM and turns its output into live React components from the vendor\'s Crayon library through a DSL, steerable by system prompt and function calling. The company\'s companion argument is that generating code for generative UI is a bad idea.',
  stance='The model composes from a vendor library, not code; the vendor\'s catalog and renderer are the guardrails.'),
 dict(key='microsoft', group='ind', motif='grid', short='Microsoft guidelines',
  title='Adaptive Cards for agent design, and UX guidelines for MCP apps in Microsoft 365 Copilot',
  meta='Microsoft, guidance dated May and June 2026',
  url='https://learn.microsoft.com/en-us/agents/design-guidelines/adaptive-cards-for-agent-design',
  summary='Cards should feel intentional, structured and designed rather than simply generated: the agent controls the data and decisions, you control layout, hierarchy and interaction. The Copilot guidelines add: extract capabilities, do not replicate interfaces; use Fluent 2; if the experience resembles your entire product it exceeds scope. A Power CAT post argues for run-time card generation and reports streaming glitches and a need to fix the number of form fields.',
  stance='Designer-authored templates with the model filling slots, inside a host that explicitly forbids rebuilding an app in chat, with an internal push toward model-generated cards.'),
 dict(key='salesforce', group='ind', motif='screen', short='Salesforce AIforce',
  title='AIforce at Dreamforce 2026, and custom Lightning types in Agentforce',
  meta='Salesforce, Sept 2026',
  url='https://www.salesforce.com/news/stories/aiforce-announcement/',
  summary='Users compose customised live interfaces on the fly by describing them, inside Slack, Claude and the Agentforce Coworker in Lightning, riding existing permissions. The executives say AI disaggregates and replaces the UI; the verified mechanism is custom Lightning types that bind developer-authored components to agent actions.',
  stance='The person describes and the platform composes from its components under its permissions; the replace-the-UI rhetoric outruns what the docs show, which is catalog selection.'),
 dict(key='shopify', group='ind', motif='screen', short='Shopify Sidekick',
  title='Sidekick builds custom admin apps',
  meta='Shopify Winter 2026 Edition, Dec 2025 (secondary source)',
  url='https://thelettertwo.com/2025/12/10/shopify-ai-growth-tools-sidekick-tinker-agentic-storefronts/',
  summary='Merchants describe an app or automation in natural language and Sidekick generates it inside the admin, powered by the Polaris design system and the Admin GraphQL API. No first-party engineering post on generative UI was found.',
  stance='The model authors whole mini-apps, constrained to the platform\'s design system and API; the design system is the guardrail.'),
 dict(key='figma', group='ind', motif='screen', short='Figma Agent',
  title='The Figma Agent, and Config 2026: Code Layers, generative plugins, Make skills',
  meta='Figma, May and June 2026',
  url='https://www.figma.com/blog/the-figma-agent-is-here/',
  summary='An agent fine-tuned for editing Figma files, addressable by mentioning tokens, variables and components, with a prompt box on the canvas and changes that land behind a loading indicator and undo with the usual shortcut. Config 2026 put live code on the canvas as Code Layers, extractable back to design layers, and let plugins be described into existence.',
  stance='The model generates design layers and code inside a team\'s design system at design time, with the designer holding the guardrails by direct manipulation; nothing here generates UI for end users at run time.'),
 dict(key='stitch', group='ind', motif='screen', short='Google Stitch',
  title='Google Stitch',
  meta='Google Labs, May 2025; multi-screen update March 2026',
  url='https://blog.google/innovation-and-ai/models-and-research/google-labs/stitch-ai-ui-design/',
  summary='Text or image prompts become high-fidelity screens and multi-screen flows, exported to HTML, Figma, Flutter or SwiftUI, with an MCP server for coding agents.',
  stance='The model authors whole screens at design time for people to edit; no run-time role and no catalog.'),
 dict(key='spectrum', group='ind', motif='figure', short='CopilotKit spectrum',
  title='The generative UI spectrum, the 2026 developer\'s guide, and AG-UI',
  meta='CopilotKit, Jan 2026',
  url='https://www.copilotkit.ai/generative-ui-spectrum',
  summary='Three bands: controlled (developer ships components, agent selects; the workhorse), declarative (A2UI and friends; where the long tail lives), open (MCP Apps, the agent owns the canvas; mostly experimental), with AG-UI as the event and state layer under all of them. Names the production pains of text-only agents: hidden tool progress, vague unvalidated inputs, opaque multi-step flows.',
  stance='A vendor taxonomy that treats all three authoring models as legitimate and argues for mixing them per surface.'),
 dict(key='spotify', group='ind', motif='list', short='Spotify Encore',
  title='Making the Encore design system AI-ready',
  meta='Spotify design systems team, Into Design Systems meetup, Feb 2026 (secondary write-up)',
  url='https://www.intodesignsystems.com/blog/how-spotify-design-system-ai-ready',
  summary='Encore built an MCP server, rewrote its docs to be machine-readable, split components into foundation, style and behaviour layers to create smaller context bubbles, and built a test harness that scores model output on lint errors, similarity and visual diff. The stated problem: the AI is not going to figure it out, it is going to put users on a different path.',
  stance='The design system becomes the machine-readable guardrail so agents generate on-system code; the system team holds the guardrails.'),
]
