# Academic HCI sources, 2024–2026. verified=False means seen only in a search snippet.
ACAD = [
 dict(key='w66', group='acad', motif='chat', short='W66 workshop',
  title='What does Generative UI mean for HCI practice?',
  meta='CHI 2026 workshop W66 · Lindley, Williams, Cao, Xia, Churchill, Sellen, Nichols, Karger',
  url='https://www.microsoft.com/en-us/research/publication/what-does-generative-ui-mean-for-hci-practice/',
  summary='The workshop proposal defines generative UI as interfaces created by AI models, covering both generation during design and generation at the point of use. Its two goals are to envision how GenUI can carry human-centred experiences and to work out how HCI and design practice should change in response; the format is a panel, ideation exercises and collaborative artefacts with about 35 participants.',
  stance='The premise of the whole event is that practice itself must change, not that a new output type has been added to an old process.'),
 dict(key='pott', group='acad', motif='grid', short='Pott taxonomy',
  title='A taxonomy and research agenda for generative user interfaces',
  meta='CHI 2026 GenUI workshop · Pott, Rietsche, Wambsganss, Söllner',
  url='https://genuimeetshci.github.io/chi26-workshop/proposals/taxonomy_research_agenda_genui_chi26_workshop.pdf',
  summary='A Nickerson-method taxonomy from a review of about 28 publications and four expert interviews: 14 dimensions in four meta-dimensions (generation process, interaction, task dynamics, contextual consideration). Morae, Misty, AmbigChat and BISCUIT are classified as worked examples, for instance element versus full regeneration and prompting-through-action.',
  stance='Asks outright how the designer\'s role evolves, and lists accessibility, consistency and security under runtime generation as the open agenda.'),
 dict(key='lee', group='acad', motif='list', short='Lee definition',
  title='Towards a working definition of designing generative user interfaces',
  meta='DIS 2025 Companion · Kyungho Lee',
  url='https://arxiv.org/abs/2505.15049',
  summary='A definition study built from a review of 127 publications, 18 expert interviews and 12 case studies. Proposes GenUI as an iterative co-creative paradigm with five characteristics (co-creation, design-space expansion, representational fluidity, contextual adaptation, generation-first) and three emerging models of practice: hybrid creation, curation, AI-assisted refinement.',
  stance='Insists on two coupled design moments: people and models co-design at design time, and users meet generated interfaces at run time. Ethics and evaluation are named as unsolved.'),
 dict(key='eardley', group='acad', motif='side', short='Eardley & Tonkin',
  title='Generative UI reshapes design practice, not design relevance',
  meta='CHI 2026 GenUI workshop · Eardley, Tonkin (Bristol)',
  url='https://research-information.bris.ac.uk/en/publications/generative-ui-reshapes-design-practice-not-design-relevance/',
  summary='From observing a real design process: GenUI tools are both useful within practice and "quixotic polishers of incomplete concepts" that gloss over information architecture and regulatory requirements. Designers keep accountability for what generation defers or hides.',
  stance='The designer\'s job shifts toward governing what the generator cannot see, rather than producing screens.'),
 dict(key='ryskeldiev', group='acad', motif='screen', short='Accessibility bridge',
  title='Generative UI as an accessibility bridge: lessons from C2C e-commerce',
  meta='arXiv 2604.25455, April 2026 (expanded CHI 2026 W66 paper) · Ryskeldiev',
  url='https://arxiv.org/abs/2604.25455',
  summary='Six studies from 2022 to 2025 with blind, low-vision and older marketplace users motivate three interventions: HTML regeneration for screen readers, conversational guidance for older sellers, and audio-guided photo framing for blind sellers.',
  stance='States directly that the designer moves from specifying layouts to specifying policies, and that GenUI complements ability-based design rather than replacing it.'),
 dict(key='saac', group='acad', motif='screen', short='Software as Content',
  title='Software as content: dynamic applications as the human-agent interaction layer',
  meta='arXiv 2603.21334, March 2026 · Xie, Xie',
  url='https://arxiv.org/abs/2603.21334',
  summary='Argues that dynamically generated applications, not chat, should be the medium between people and agents, because chat cannot hold structured data, is high-entropy, and keeps no evolving state. Formalises a human, agent, environment model and derives principles for applications that converge toward personal, task-specific software.',
  stance='The design unit is the lifecycle of an evolving application, treated as a tractable research object in its own right.'),
 dict(key='google', group='acad', motif='screen', short='Google GenUI paper',
  title='Generative UI: LLMs are effective UI generators',
  meta='arXiv 2604.09577, Feb 2026 · Leviathan, Valevski, Kalman et al. (Google Research, DeepMind)',
  url='https://arxiv.org/abs/2604.09577',
  summary='The paper behind Gemini\'s generative UI. Unconstrained generation of full HTML, CSS and JavaScript experiences from any prompt, using prompting, tool access and post-processors for error fixing and framework checks. Raters overwhelmingly prefer generated UIs to markdown and rate them at least comparable to expert-crafted pages in half of cases; releases the PAGEN expert-built evaluation set.',
  stance='Design work is relocated into the system prompt, the tool set and the post-processing pipeline; evaluation is preference on whole experiences against expert references, not usability of a fixed design.'),
 dict(key='geninterfaces', group='acad', motif='chat', short='Generative Interfaces',
  title='Generative interfaces for language models',
  meta='ACL 2026 Findings; arXiv 2508.19227 · Chen, Zhang, Zhang, Shao, Yang (Stanford)',
  url='https://arxiv.org/abs/2508.19227',
  summary='The model answers a query by proactively generating a task-specific web UI through a structured intermediate representation and a reward-driven refinement loop. Introduces a three-axis evaluation (functional, interactive, emotional) against chat; reports up to 72% improvement in human preference.',
  stance='The decision is when and what to generate per query, and evaluation needs axes that plain task success does not cover.'),
 dict(key='jelly', group='acad', motif='grid', short='Jelly',
  title='Generative and malleable user interfaces with generative and evolving task-driven data model',
  meta='CHI 2025 · Cao, Jiang, Xia (UC San Diego)',
  url='https://arxiv.org/abs/2503.04084',
  summary='Instead of generating code, the model generates a task-driven data model (entities, relationships, data) that is mapped to UI specifications. People tailor the interface by language and direct manipulation, and the edits flow back into the model. Jelly is the prototype.',
  stance='Designing for GenUI means designing the representation that persists and evolves, not the screen. Code-first generation is criticised for blocking iterative end-user tailoring.'),
 dict(key='modi', group='acad', motif='side', short='Malleable ODI',
  title='Malleable overview-detail interfaces',
  meta='CHI 2025 · Min, Chen, Cao, Xia (UC San Diego)',
  url='https://arxiv.org/abs/2503.07782',
  summary='A content analysis of the overview-detail pattern yields three dimensions of variation (content, composition, layout). Fluid Attributes lets people show and hide attributes across views and use AI to manipulate, reformat and generate attributes, plus techniques to compose views and transform layouts. Two design probes.',
  stance='The designer ships a design space over a pattern and the end user picks the point in it; AI generation is scoped to attributes inside that space.'),
 dict(key='gradual', group='acad', motif='list', short='Gradual Generation',
  title='Gradual generation of user interfaces as a design method for malleable software',
  meta='arXiv 2601.17975, Jan 2026 · Min, Jiang, Huang, Xia (UC San Diego)',
  url='https://arxiv.org/abs/2601.17975',
  summary='Names a trade-off that conventional UI does not have: prompt boxes keep the model\'s expressiveness but offer no way to discover customisations, while menus cannot scale to the space AI opens. Proposes intermediate UI layers that the model loads gradually and that people can reverse to reach the customisation they want.',
  stance='Explicitly a GenUI design method: the designer authors the staging of the dimensions along which generation unfolds, not final layouts.'),
 dict(key='gulfs', group='acad', motif='figure', short='Bridging Gulfs',
  title='Bridging gulfs in UI generation through semantic guidance',
  meta='CHI 2026; arXiv 2601.19171 · Park, Lee, Choi, Kim, Kweon, Song, Seo (SNU)',
  url='https://arxiv.org/abs/2601.19171',
  summary='A thematic analysis of UI prompting guidelines surfaces hierarchical, interdependent design semantics. A system lets people specify semantics, see their relationships, and extract how each landed in the generated UI, as an intermediate representation between intent and output. Users reported more control and more predictable iteration.',
  stance='Applies Norman\'s gulfs of execution and evaluation to generation itself: the new problem is elicitation and legibility of intent, not layout.'),
 dict(key='jit', group='acad', motif='figure', short='JIT Objectives',
  title='Just-in-time objectives: a general approach for specialized AI interactions',
  meta='CHI 2026; arXiv 2510.14591 · Lam, Shaikh, Xu, Guo, Yang, Heer, Landay, Bernstein',
  url='https://arxiv.org/abs/2510.14591',
  summary='Infers a person\'s current objective from passively observed behaviour and uses it to steer and judge model output, including on-demand tool generation. Reports 66 to 86% win rates over standard output, and in-person sessions rated generated tools well above chat.',
  stance='The specification the system optimises against is inferred just in time, so the interface\'s requirements are written by an objective model rather than by a designer up front.'),
 dict(key='maru', group='acad', motif='grid', short='Maru',
  title='Maru: information architecture as a shared language for generating aligned and persistent user interfaces',
  meta='arXiv 2608.25565, Aug 2026 · Kim, Choi, Min, Yi, Jiang, Kim (KAIST, UC San Diego)',
  url='https://arxiv.org/abs/2608.25565',
  summary='Generated interfaces re-decide structure at every generation and drift from what the person had established. Four IA elements (partition, hierarchy, order, vocabulary) are mapped to generation decisions, and a conversational system captures prompts and interactions as persistent IA rules. With persistence, generations stayed aligned over a session; without it they degraded.',
  stance='Names a new evaluation unit and artefact: cross-generation alignment, carried by a persistent IA layer the person and the model share.'),
 dict(key='sreedhar', group='acad', motif='list', short='Conversational customization',
  title='Conversational customization of productivity systems: a design probe of malleable AI interfaces',
  meta='arXiv 2605.11149, May 2026 · Sreedhar, Kaul, Chilton (Columbia)',
  url='https://arxiv.org/abs/2605.11149',
  summary='A multi-day probe of an email client people modify by natural language inside their real workflows. Modifications adapted existing patterns rather than inventing new functionality, and malleability brought new risks (mis-specified behaviour, unintended filtering, uncertain outcomes) that people managed by continuous oversight.',
  stance='Field evidence that GenUI design has to budget for guardrails and reversibility, because the end user\'s own specification is the failure surface.'),
 dict(key='taleoftwo', group='acad', motif='screen', short='Tale of Two Designs',
  title='Rethinking the UI of GenUI: a tale of two designs',
  meta='arXiv 2606.13843, June 2026 · Chen, Petridis, Deng, Bari, Du, Li (UCLA, Google)',
  url='https://arxiv.org/abs/2606.13843',
  summary='Most GenUI design tools inherit chatbot conventions: unstructured prompt, depth-first, high fidelity. A contrastive tool (structured input, breadth-first, low fidelity) is compared with 24 designers and product managers. Structure surfaces facets but raises entry cost; breadth reveals more but is hard to preview; professionals still want fidelity.',
  stance='The generator\'s own interface is a design object with its own trade-offs, and generation reshapes what professionals expect of fidelity.'),
 dict(key='taskartisan', group='acad', motif='grid', short='TaskArtisan',
  title='TaskArtisan: designing composable generative widgets for LLM-assisted analysis',
  meta='VL/HCC 2026; arXiv 2607.17394 · Chen, Pavel',
  url='https://arxiv.org/abs/2607.17394',
  summary='Interviews with six professionals, an analysis of publicly shared generated GUI tools, and a 12-person comparison of a chatbot against a probe where people create and compose generative widgets. Generated GUIs improved clarity but introduced rigidity and new prompting problems; the reuse benefit came from modular composition.',
  stance='Three considerations specific to generated UI: malleability, specification, interoperability. The question is how pieces are re-specified and recombined, not how one screen looks.'),
 dict(key='athena', group='acad', motif='grid', short='Athena',
  title='Athena: intermediate representations for iterative scaffolded app generation with an LLM',
  meta='arXiv 2508.20263, Aug 2025 · Beason, Cheng, Schoop, Nichols (Apple)',
  url='https://arxiv.org/abs/2508.20263',
  summary='Storyboard, data model and GUI skeletons serve as shared intermediate representations between a person and the generator, so an app is built up in scaffolded steps rather than regenerated. Three quarters of participants preferred it to chat.',
  stance='Part of Apple\'s IR line: the design object is the representation that both parties can edit, chosen so that what will and will not change is legible.'),
 dict(key='squire', group='acad', motif='grid', short='SQUIRE', verified=False,
  title='SQUIRE: interactive UI authoring via slot query intermediate representations',
  meta='UIST 2025 · Leung, Cheng, Wu, Nichols, Barik (Apple)',
  url='https://doi.org/10.1145/3746059.3747672',
  summary='A slot-based intermediate representation for UI authoring with guarantees about which parts of the interface a request will and will not mutate. Seen only in search results; the summary is from the title and snippet.',
  stance='Guarantees about what stays fixed are treated as the thing the designer authors, which is the constrained end of the field\'s central disagreement.'),
 dict(key='duetui', group='acad', motif='figure', short='DuetUI',
  title='DuetUI: a bidirectional context loop for human-agent co-generation of task-oriented interfaces',
  meta='arXiv 2509.13444, Sept 2025, revised Feb 2026 · Xu et al.',
  url='https://arxiv.org/abs/2509.13444',
  summary='The agent scaffolds an interface by decomposing the task; the person\'s direct manipulation of the result steers the next generation step. A 12-person formative study and a 24-person comparison.',
  stance='Generation is a loop in which manipulation is a specification act, so the design object includes what the model reads back from the person\'s use.'),
 dict(key='genuistudy', group='acad', motif='list', short='The GenUI Study',
  title='The GenUI study: exploring the design of generative UI tools to support UX practitioners and beyond',
  meta='arXiv 2501.13145, Jan 2025 · Chen, Knearem, Li',
  url='https://arxiv.org/abs/2501.13145',
  summary='Thirty-seven practitioners ran week-long projects with GenUI tools. Four roles the tools play in practice are identified, along with where the tools help and where they get in the way.',
  stance='Treats GenUI mainly as tooling for professionals, which is one side of the runtime-versus-design-time split in how the field defines the activity.'),
 dict(key='debt', group='acad', motif='list', short='Hidden technical debt',
  title='Hidden technical debt in generative and malleable user interfaces',
  meta='CHI 2026 GenUI workshop; arXiv 2604.16354 · Cifliku',
  url='https://arxiv.org/abs/2604.16354',
  summary='Catalogues the barriers that generated and malleable interfaces accumulate underneath the visible screen: adaptable data formats, security protocols, and the skill gaps of the people expected to steer them.',
  stance='The activity includes designing the substrate the interface changes over, which conventional UI design takes as given.'),
 dict(key='dynavis', group='acad', motif='figure', short='DynaVis',
  title='DynaVis: dynamically synthesized UI widgets for visualization editing',
  meta='CHI 2024 (best paper) · Vaithilingam, Arawjo, Glassman et al.',
  url='https://doi.org/10.1145/3613904.3642639',
  summary='Pairs natural language with synthesised widgets: a request to edit a chart yields a small control for that exact edit, so the person can keep adjusting without re-prompting. An early and much-cited demonstration that a generated control can be the answer to a request.',
  stance='The earliest clean case of the generator producing an affordance rather than an outcome, which is the move the later design-method papers build on.'),
 dict(key='biscuit', group='acad', motif='grid', short='BISCUIT',
  title='BISCUIT: scaffolding LLM-generated code with ephemeral UIs in computational notebooks',
  meta='VL/HCC 2024 · Cheng, Barik, Leung, Hohman, Nichols (Apple)',
  url='https://arxiv.org/abs/2404.07387',
  summary='Ephemeral, generated micro-interfaces in a notebook let people set the parameters of code the model is about to write, instead of describing them in prose.',
  stance='Generated UI as a transient specification surface, made for one step and discarded, which is the opposite lifecycle from Maru and Jelly.'),
 dict(key='misty', group='acad', motif='screen', short='Misty',
  title='Misty: UI prototyping through interactive conceptual blending',
  meta='CHI 2025 · Lu et al. (Apple)',
  url='https://doi.org/10.1145/3706598.3713924',
  summary='Designers blend an existing UI with example screens or sketches and the model generates the blended prototype, keeping the interaction in the space of examples rather than prompts.',
  stance='A design-time GenUI tool whose input vocabulary is examples, one answer to the elicitation problem the run-time systems face.'),
]
